---
title: "Mai_filtering_osv"
output: html_document
---

```{r}
library(phyloseq)
library(ggplot2)
library(tidyverse)
library(vegan)
```


```{r}
load("C:/Users/mai/OneDrive/Documents/Uni/Metagenomic Analyses of Microbiomes/Projekt/diabetes_t2_D003924/D003924_Diabetes_Mellitus,_T/genus/phyloseq.RData")

ps <- pylsq #Viser et overblik over phyloseq-objektet.

sample_data(ps) #viser meta data for alle samples
rank_names(ps) #Viser hvilke taxonomiske niveauer der findes.
sample_variables(ps) #Viser navnene på metadata-kolonnerne.
```

Filtrere så vi kun beholder project ID
```{r}
ps_filtered <- subset_samples(
  ps,
  Project.ID == "PRJNA422434"
)
```



```{r}
# Calculate Shannon diversity for all samples
shannon <- estimate_richness(
  ps_filtered,
  measures = "Shannon"
)

head(shannon)
```


visualizing alpha diversity
```{r}
plot_richness(
  pylsq,
  measures = "Shannon"
)
```




```{r}
plot_richness(
  pylsq,
  measures = "Shannon",
  x = "Disease.MESH.ID",
) +
  geom_boxplot(
    aes(group = Disease.MESH.ID),
    alpha = 0.4,
    outlier.shape = NA
  )
```



```{r}
ps_pa <- transform_sample_counts(ps_filtered, function(x) {ifelse(x > 0, 1, 0)})

# Calculate Shannon diversity
shannon <- estimate_richness(
  ps_filtered,
  measures = "Shannon"
) %>%
  rownames_to_column("sample_id")

# Calculate observed richness
observed <- estimate_richness(
  ps_pa,
  measures = "Observed"
) %>%
  rownames_to_column("sample_id")

# Extract sample metadata
sample_df <- sample_data(ps_filtered) %>%
  data.frame() %>%
  rownames_to_column("sample_id")

# Combine diversity estimates and metadata
alpha_diversity <- inner_join(
  shannon,
  observed,
  by = "sample_id"
) %>%
  inner_join(
    sample_df,
    by = "sample_id"
  )
```


```{r}
kruskal_shannon <- kruskal.test(
  Shannon ~ Disease.MESH.ID,
  data = alpha_diversity
)

kruskal_shannon
```
nu er p-værdien mindre signifikant, det skyldes nok at de andre projekter havde samples som var mere forskellige fra kina projektet og da der kun var diseased i de projekter, fik det måske diseased til at se mere anderledes ud end det var.


BETA diversity
```{r}
ps_rel <- transform_sample_counts(
  ps_filtered,
  function(x) x / sum(x)
)

bray_dist <- distance(
  ps_rel,
  method = "bray"
)

```



```{r}
ord_bray <- ordinate(
  ps_rel,
  method = "PCoA",
  distance = bray_dist
)

plot_ordination(
  ps_rel,
  ord_bray,
  type = "samples",
  color = "Disease.MESH.ID"
)
```

