---
title: "filtering"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Loading libraries
```{r}
library(phyloseq)
library(ggplot2)
library(vegan)
library(dplyr)
library(tibble)
```

```{r}
load("project/data/D003924_Diabetes_Mellitus,_T/genus/phyloseq.RData")
ps_genus <- pylsq
rm(pylsq)

load("project/data/D003924_Diabetes_Mellitus,_T/species/phyloseq.RData")
ps_species <- pylsq
rm(pylsq)

ps_genus
ps_species
```
Balance between healthy and sick
```{r}
table(sample_data(ps_genus)$Disease.MESH.ID, useNA = "ifany")
```

PRJEB1786 is Europe, PRJNA299502 is USA, PRJNA422434 is China 
```{r}
table(sample_data(ps_genus)$Project.ID, useNA = "ifany")
```
Combined
```{r}
table(sample_data(ps_genus)$Project.ID,
      sample_data(ps_genus)$Disease.MESH.ID)
```
Combined and country as well
```{r}
table(sample_data(ps_genus)$Country,
      sample_data(ps_genus)$Project.ID)
```

```{r}
table(sample_data(ps_genus)$Country,
      sample_data(ps_genus)$Disease.MESH.ID)
```

```{r fig.width=8, fig.height=5}
ps_rel <- transform_sample_counts(ps_genus, function(x) x / sum(x))
bray_dist <- distance(ps_rel, method = "bray")
ord_bray <- ordinate(ps_rel, method = "PCoA", distance = bray_dist)

plot_ordination(ps_rel, ord_bray, color = "Project.ID") +
  geom_point(size = 2, alpha = 0.7) +
  stat_ellipse() +
  theme_bw() +
  labs(title = "Bray–Curtis PCoA coloured by cohort",
       subtitle = "Three distinct clusters; PRJEB1786 and PRJNA299502 sit apart from PRJNA422434")
```

```{r adonis-adjusted}
sample_df <- sample_data(ps_rel) |> data.frame()

adonis2(bray_dist ~ Project.ID + Disease.MESH.ID,
        data = sample_df,
        by = "margin",
        permutations = 999)
```

